### ISSUE TITLE
Instructions unclear for number resource and properties.

### ISSUE THREAD

**Issue by Namphibian** [agoncal/agoncal-fascicle-quarkus-pract#12]
Hi Team.

Just a bit of constructive feedback.

When following along with the instructions for Chapter 4 there is a bit of confusion. With developers delight in mind I just wanted to point it out to you. 

The listing (4.2.1) for the NumberResource class given as:

````
@Path("/api/numbers/book")
public class NumberResource {
  private static final Logger LOGGER = Logger.getLogger(NumberResource.class);
  @GET
  @Produces(MediaType.APPLICATION_JSON)
  public Response generateBookNumbers() throws InterruptedException {
    LOGGER.info("Generating book numbers");
    Faker faker = new Faker();
    BookNumbers bookNumbers = new BookNumbers();
    bookNumbers.setIsbn10(faker.code().isbn10(separator));
    bookNumbers.setIsbn13(faker.code().isbn13(separator));
    bookNumbers.setAsin(faker.code().asin());
    bookNumbers.setEan8(faker.code().ean8());
    bookNumbers.setEan13(faker.code().ean13());
    bookNumbers.setGenerationDate(Instant.now());
    return Response.ok(bookNumbers).build();
    }
}

````

The next section(4.2.2) mentions the object model with this code.
````
public class BookNumbers {
  private String isbn10;
  private String isbn13;
  private String asin;
  private String ean8;
  private String ean13;
  private Instant generationDate;
}

````
The next sentence mentions "As you can see, the definition for the separator is missing and for that reason, the code of the
Number REST endpoint does not compile yet...."

However the property is missing from both the classes. I could work out where the property is supposed to go by looking at the completed examples however it required me to do a bit of back tracking.  If you added the property to the code in the example it would make it easier to follow for developers... making them happy.

Thanks for the effort.

**Comment by agoncal** [comment]
Thanks for the feedback @Namphibian. I think I'll add the property `separator` (so the code compiles) and then introduce configuration injection. You are right. This way the developer will have code that compiles and works.

Thanks
